/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.boletim.view;

import br.com.boletim.control.LimitadorDeCaracteres;
import br.com.boletim.control.TelaControl;
import br.com.boletim.control.Utils;

/**
 *
 * @author Alunos
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    private TelaControl control;

    public Tela() {
        initComponents();
        control = new TelaControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastros de Notas");
        setMinimumSize(new java.awt.Dimension(360, 330));
        setPreferredSize(new java.awt.Dimension(360, 360));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 18, -1, -1));

        jLabel2.setText("Matrícula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 65, -1, -1));

        jLabel3.setText("Sobrenome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 15, -1, -1));

        jLabel4.setText("Nivel:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 65, -1, -1));
        getContentPane().add(tfSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 15, 100, -1));
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 100, -1));
        getContentPane().add(tfMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 62, 100, -1));

        getContentPane().add(cbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 62, 100, -1));

        jLabel5.setText("NP1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 132, -1, -1));

        jLabel6.setText("Peso das Provas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, -1, -1));

        tfNP1.setDocument(new LimitadorDeCaracteres(4));
        getContentPane().add(tfNP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 132, 30, -1));

        jLabel7.setText("NP2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 132, -1, -1));

        tfNP2.setDocument(new LimitadorDeCaracteres(4));
        getContentPane().add(tfNP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 132, 30, -1));

        tfPesoProvas.setDocument(new LimitadorDeCaracteres(3));
        tfPesoProvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfPesoProvasMouseEntered(evt);
            }
        });
        getContentPane().add(tfPesoProvas, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 180, 30, -1));

        jLabel8.setText("T1:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 132, -1, -1));

        jLabel9.setText("Peso dos Trabalhos:");
        jLabel9.setAlignmentX(0.5F);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        tfT1.setDocument(new LimitadorDeCaracteres(4));
        getContentPane().add(tfT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 132, 30, -1));

        jLabel10.setText("T2:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 132, -1, -1));

        tfT2.setDocument(new LimitadorDeCaracteres(4));
        getContentPane().add(tfT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 132, 30, -1));

        tfPesoTrabalhos.setDocument(new LimitadorDeCaracteres(3));
        tfPesoTrabalhos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfPesoTrabalhosMouseEntered(evt);
            }
        });
        getContentPane().add(tfPesoTrabalhos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 30, -1));

        jLabel11.setText("Média:");
        jLabel11.setToolTipText("oiii");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jLabel11.getAccessibleContext().setAccessibleDescription("");

        jLabel13.setText("Situação:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 232, -1, -1));

        jButton1.setText("Salvar e Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 262, 155, 50));

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 262, 155, 50));

        lblSituacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSituacao.setText("........");
        getContentPane().add(lblSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 232, -1, -1));

        lblMedia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMedia.setText(".......");
        getContentPane().add(lblMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 360, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 360, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 360, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 360, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        control.salvarAction();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Utils.clearFields();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfPesoProvasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPesoProvasMouseEntered
        control.toolTipAction(tfPesoProvas);      // TODO add your handling code here:
    }//GEN-LAST:event_tfPesoProvasMouseEntered

    private void tfPesoTrabalhosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPesoTrabalhosMouseEntered
        control.toolTipAction(tfPesoTrabalhos);
     }//GEN-LAST:event_tfPesoTrabalhosMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JComboBox<String> cbNivel = new javax.swing.JComboBox<>();
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public static final javax.swing.JLabel lblMedia = new javax.swing.JLabel();
    public static final javax.swing.JLabel lblSituacao = new javax.swing.JLabel();
    public static final javax.swing.JTextField tfMatricula = new javax.swing.JTextField();
    public static final javax.swing.JTextField tfNP1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField tfNP2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField tfNome = new javax.swing.JTextField();
    public static final javax.swing.JTextField tfPesoProvas = new javax.swing.JTextField();
    public static final javax.swing.JTextField tfPesoTrabalhos = new javax.swing.JTextField();
    public static final javax.swing.JTextField tfSobrenome = new javax.swing.JTextField();
    public static final javax.swing.JTextField tfT1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField tfT2 = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
